declare module '@gmod/jbrowse-core/configuration'
declare module '@gmod/jbrowse-core/PluginManager'
declare module '@gmod/jbrowse-core/rpc/RpcManager'
declare module '@gmod/jbrowse-core/assemblyManager'
declare module '@gmod/jbrowse-core/configuration/configurationSchema'
declare module '@gmod/jbrowse-core/util/tracks'
